#!/bin/sh

rm -r docs

for p in \
    berean-interlinear paginated-morphgnt-interlinear sblgnt-web \
    static-paginated-perseus4 toggle-controls
do
    echo "building $p"
    mkdir -p docs/$p
    (cd prototypes/$p; rm -r output; ./generate.py)
    cp prototypes/$p/output/* docs/$p
done

echo "This directory generated by make-gh-pages.sh" > docs/README.md
